#TO PRINT EVEN NUMBERS FROM 1-100
#THE EVEN IDEA IS ANY NUMBER DIVISIBLE BY 2 OR INCREMENTING FROM 2 BY ADDING 2 TO IT SELF UNTIL IT REACHES A CONDITION WHICH IS 100
#THEN PRINT THE THE RESULT

number = 2
for count in range(number, 100+1, 2):
    print(count)
