#TO CALCULATE THE MULTIPLE OF 3
#COLLECT THE INPUT WHICH IS 3
#THE MULTIPLE OF THREE IS ADDING 3 TO IT SELF UNTIL IT REACHES A CONDITION WHICH IS #*15
#THEN PRINT THE THE RESULT

total = 0
number = 3
for count in range(number, (3*15)+1, 3):
    print(count)
