#TO CALCULATE THE SUM
#COLLECT THE INPUT WHICH IS 10
#THE MULTIPLE OF TEN IS ADDING 10 TO IT SELF UNTIL IT REACHES A CONDITION WHICH IS 20_000
 #THEN STORE ALL COUNT AND KEEP ADDING THEM AS THEY COME IN
#THEN PRINT THE THE RESULT

total = 0
number = 10
for count in range(number, 20000+1, 10):
    total = total +  count

print(total)
